pre-release stabilization
flexn-io/renative pull request #1364
Opened 2024-01-26 04:27 UTC by pavjacko

## Description

- Stabilization fixes, improvements

## Related issues

- https://github.com/flexn-io/renative/issues/1357

## Npm releases

n/a

2024-01-26 07:53 UTC, GabrieleKaceviciute commented
```➜  ~/Desktop/tests/renative/packages/app-harness git:(fix/release-hotfixes) npx rnv run -p ios

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.9                                                   │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv run -p ios                                                  │
│        Start Time: 1/26/2024, 9:33:39 AM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ info ] Engines: @rnv/engine-rn,@rnv/engine-rn-tvos,@rnv/engine-rn-next,@rnv/engine-rn-web,@rnv/engine-rn-electron require plugins react,react-art,react-dom to be added to ./renative.json
? Continue?.
If you don't want to use this dependency make sure you remove platform which requires this engine from supportedPlatforms Yes
[ info ] Adding react,react-art,react-dom. ...DONE
[ task ] loadEnginePackageDeps[1]
[ task ] configurePlugins[1]
[ success ] This project is marked as part of monorepo and it has no custom install tasks. Run your usual monorepo bootstrap procedure and re-run command again.
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 1/26/2024, 9:33:52 AM                                         │
│  $ npx rnv run -p ios                                                        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.9                                                │
│  Project Name ($package.name): @rnv/app-harness                              │
│  Project Version ($package.version): 1.0.0-rc.9                              │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): ios                                                          │
│  App Config (-c): harness                                                    │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.19.0                                      │
│  Executed Time: 0h:0m:12s:551ms                                              │
│                                                                              │
│ [ success ] This project is marked as part of monorepo and it has no custom install tasks. Run your usual monorepo bootstrap procedure and re-run command again.
│ [ error ] Cancelled
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/tests/renative/packages/app-harness git:(fix/release-hotfixes) ✗

2024-01-26 08:12 UTC, pauliusguzas commented
And when running second time after that cancelled error, bundle install is still trigered
```pauliusguzas@MBP-de-Flexn app-harness % npx rnv run -p ios

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.9                                                   │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv run -p ios                                                  │
│        Start Time: 1/26/2024, 10:08:57 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:undefined port:NaN hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:harness
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] _applyTemplate[1] current:@rnv/template-starter selected:undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:harness
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:201.13 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:201.13 KB
[ task ] [app configure] generateBuildConfig[3] size:201.13 KB
[ task ] [app configure] generateBuildConfig[4] size:201.13 KB
[ task ] [app configure] generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:216.82 KB
[ task ] [app configure] generateBuildConfig[6] size:216.82 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:216.82 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:216.82 KB
[ info ] [app configure] Current App Config: harness
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:1.0.0-rc.9,rnvProject:1.0.0-rc.9[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:harness
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ success ] [project configure] /react-native-gesture-handler/ios/Handlers/RNHoverHandler.m requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
[ success ] [project configure] /react-native-gesture-handler/ios/RNGestureHandlerButtonComponentView.mm requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
[ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
[ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/findMatchingSimulator.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
[ success ] [project configure] /@react-native-community/cli-platform-ios/build/commands/runIOS/index.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
[ info ] [project configure] Plugin overrides disabled for: next with disablePluginTemplateOverrides. SKIPPING
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkSdk[1]
[  [...]

2024-01-26 09:51 UTC, pauliusguzas requested changes
```
pauliusguzas@MBP-de-Flexn app-harness % npx rnv run -p tvos

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.9                                                   │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv run -p tvos                                                 │
│        Start Time: 1/26/2024, 11:49:58 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-tvos[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-tvos path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:undefined port:NaN target:undefined hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:harness
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] _applyTemplate[1] current:@rnv/template-starter selected:undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:harness
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:201.13 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:201.13 KB
[ task ] [app configure] generateBuildConfig[3] size:201.13 KB
[ task ] [app configure] generateBuildConfig[4] size:201.13 KB
[ task ] [app configure] generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:216.82 KB
[ task ] [app configure] generateBuildConfig[6] size:216.82 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:216.82 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:216.82 KB
[ info ] [app configure] Current App Config: harness
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:1.0.0-rc.9,rnvProject:1.0.0-rc.9[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:harness
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] /react-native-gesture-handler/ios/Handlers/RNHoverHandler.m overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json
[ info ] [project configure] /react-native-gesture-handler/ios/RNGestureHandlerButtonComponentView.mm overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/tools/findMatchingSimulator.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/commands/runIOS/index.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] Plugin overrides disabled for: next with disablePluginTemplateOverrides. SKIPPING
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:harness
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] t [...]

2024-01-26 11:26 UTC, pavjacko commented
> And when running second time after that cancelled error, bundle install is still trigered
>  

@pauliusguzas this is expected outcome. lockfile only gets generated after install is complete

2024-01-26 15:10 UTC, pauliusguzas requested changes
`npx rnv target launch -p ios`  fails on both harness and template
```
pauliusguzas@MBP-de-Flexn app-harness % npx rnv target launch -p ios

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.9                                                   │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv target launch -p ios                                        │
│        Start Time: 1/26/2024, 5:02:55 PM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-core/lib
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] target launch
[ task ] => [target launch]
[ task ] [target launch] taskRnvTargetLaunch[1]
[ task ] [target launch] isPlatformSupported[1]
[ task ] [target launch] checkAndConfigureSdks[1]
[ task ] => [target launch] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [target launch] <= workspace configure
[ task ] [target launch] checkSdk[1]
[ task ] [target launch] launchAppleSimulator[1] iPhone 14
[ task ] [target launch] getAppleDevices[1] ignoreDevices:true ignoreSimulators:undefined
✔ Executing: xcrun simctl list --json
[ info ] [target launch] Launching: iPhone 14 (use -t to use different target)...
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 1/26/2024, 5:02:56 PM                                         │
│  $ npx rnv target launch -p ios                                              │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.9                                                │
│  Project Name ($package.name): @rnv/app-harness                              │
│  Project Version ($package.version): 1.0.0-rc.9                              │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): ios                                                          │
│  Engine ($.platforms.ios.engine): engine-core                                │
│  App Config (-c): harness                                                    │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.17.0                                      │
│  Executed Time: 0h:0m:1s:467ms                                               │
│                                                                              │
│ [ error ] [target launch] COMMAND:

xcrun simctl boot 6F0CD255-F21F-4B8F-B6BB-384E3B04C665

FAILED with ERROR:

Command failed with exit code 149: xcrun simctl boot 6F0CD255-F21F-4B8F-B6BB-384E3B04C665

Error: Command failed with exit code 149: xcrun simctl boot 6F0CD255-F21F-4B8F-B6BB-384E3B04C665
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn app-harness %
```
times for running:
Executed Time: 0h:9m:54s:842ms - harness ios
Executed Time: 0h:6m:26s:67ms - harness tvos
Executed Time: 0h:9m:53s:727ms - template ios
Executed Time: 0h:5m:34s:923ms - template tvos

run time issue seems to be fixed

2024-01-26 15:11 UTC, GabrieleKaceviciute commented
`npx rnv run -p ios` :
harness -> Executed Time: 0h:7m:27s:849ms
:exclamation:template -> Executed Time: 0h:15m:3s:960ms
`npx rnv run -p tvos` :
harness -> Executed Time: 0h:4m:34s:866ms
template -> Executed Time: 0h:6m:27s:410ms

2024-01-29 13:08 UTC, pauliusguzas approved these changes

2024-01-29 13:08 UTC, merged