android -> -t do not ask to select device/simulator when needed
flexn-io/renative pull request #1385
Opened 2024-02-11 13:28 UTC by ElenaDiachenko

## Description

- npx rnv run -p android -t do not ask to select target if there is active at least one device or at least one simulator.

## Related issues

- https://github.com/flexn-io/renative/issues/1367

## Npm releases

n/a

2024-02-12 09:11 UTC, mihaiblaga89 requested changes

2024-02-12 09:11 UTC, mihaiblaga89 commented on packages/sdk-android/src/runner.ts
> +export const isString = (target: boolean | string): boolean => {
why export it from `runner`? Either don't export it and prefix it with _, so we know it's private or move this to some utils and import it from there.

2024-02-12 12:22 UTC, mihaiblaga89 approved these changes

2024-02-12 14:25 UTC, pauliusguzas requested changes
`npx rnv run -p android -t non_existing_sim` should fallback to asking from list from ALL TARGETS
`npx rnv run -p android -t 111.111.111.111` should fallback to asking from list from ALL TARGETS
`npx rnv run -p android -d -t non_existing_device` should fallback to asking from list from DEVICES
`npx rnv run -p android -d -t 111.111.111.111` should fallback to asking from list from DEVICES

2024-02-13 07:55 UTC, pauliusguzas requested changes
`npx rnv run -p android -d -t non_existing_device `should fallback to asking from list from DEVICES
`npx rnv run -p android -d -t 111.111.111.111` should fallback to asking from list from DEVICES

these two whould fallback to ask from devices only, now it fallbacks to all targets

2024-02-13 08:19 UTC, pauliusguzas approved these changes

2024-02-13 09:07 UTC, merged