change android selector text
flexn-io/renative pull request #1386
Opened 2024-02-11 16:06 UTC by Marius456

## Description

-  Change android selector question text
-  Rename variable to be more universal

## Related issues

- https://github.com/flexn-io/renative/issues/1371

## Npm releases

n/a

2024-02-12 10:10 UTC, mihaiblaga89 approved these changes

2024-02-12 13:48 UTC, pauliusguzas requested changes
npx rnv target launch -p android -t
```
? What emulator would you like to launch?
  Pixel_6 | Phone 📱  | arch: arm64-v8a | udid: adb-1C011FDF6003E5-Iac2B2._adb-tls-connect._tcp. (device)  (active
)
  Pixel_4_API_29 | Phone 📱  | arch: x86 | udid: unknown
❯ Pixel_6_API_33 | Phone 📱  | arch: x86_64 | udid: unknown
```
ios and android will be fully tested after this fix, tizen in progress

2024-02-12 17:12 UTC, pauliusguzas requested changes

2024-02-12 17:12 UTC, pauliusguzas commented on packages/sdk-tizen/src/deviceManager.ts
> +                `There is no target connected! Let's try to launch it. "${chalk().white.bold(
Can't find an rnv command to reproduce this

2024-02-12 17:12 UTC, pauliusguzas commented on packages/sdk-tizen/src/deviceManager.ts
> +                message: 'On what target would you like to run the app?',
Can't find an rnv command to reproduce this

2024-02-13 08:12 UTC, pauliusguzas approved these changes

2024-02-13 08:12 UTC, merged