Fix/obj c injections
flexn-io/renative pull request #1416
Opened 2024-02-22 16:24 UTC by ElenaDiachenko

## Description

- fix objective C injections and definition of `application:didReceiveRemoteNotification:fetchCompletionHandler`

## Related issues

- n/a

## Npm releases

n/a

2024-02-26 09:52 UTC, pavjacko requested changes

2024-02-26 09:52 UTC, pavjacko commented on packages/sdk-apple/src/types.ts
> +        didReceiveNotificationResponse: SwiftMethod;
@ElenaDiachenko this is now ObjC parser but we have SwiftMethod as type

2024-02-27 08:48 UTC, pavjacko requested changes
@ElenaDiachenko can you add example snippet of how this would be configured in renative.json

2024-02-28 10:17 UTC, pauliusguzas commented
Testing steps:
1. run app-harness on ios simulator
2. go to https://icloud.developer.apple.com/dashboard/notifications
3. choose correct app id (in this case renative.harness.debug)
4. copy device token which can be seen in cli logs of the run command
5. add any name 
6. click send -> notification should appear on simulator

2024-02-28 10:18 UTC, pauliusguzas approved these changes

2024-02-28 10:28 UTC, pavjacko approved these changes

2024-02-28 10:59 UTC, merged