Fix/app harness
flexn-io/renative pull request #1447
Opened 2024-03-07 07:49 UTC by ElenaDiachenko

## Description

- Added  logging functionality to display console.logs within the app interface

## Related issues

- GH issues

## Npm releases

n/a

2024-03-08 07:51 UTC, mihaiblaga89 commented on packages/app-harness/src/app/index.tsx
> +                        <NewModuleButton handleLogs={logDebug} />
why not use the useLogger hook there directly?

2024-03-08 08:33 UTC, mihaiblaga89 approved these changes

2024-03-08 10:17 UTC, GabrieleKaceviciute requested changes
- no info on androidwear (Wear OS Square API 30)

![a_waer](https://github.com/flexn-io/renative/assets/106537292/9c70566a-1dbe-4148-a092-1f80e726b8dd)

- ios -> text doesn't fit and is cut off
![ios](https://github.com/flexn-io/renative/assets/106537292/f2ea0177-3e8c-4d78-a361-6301befd8497)

2024-03-12 09:50 UTC, GabrieleKaceviciute approved these changes

2024-03-15 11:55 UTC, pauliusguzas approved these changes

2024-03-15 20:47 UTC, merged