Fix/resolve peer deps npm
flexn-io/renative pull request #1558
Opened 2024-05-17 13:02 UTC by ElenaDiachenko

## Description

- when using NPM as package manager rnv run gets stuck in endless loop
- fixed determining of the current package manager (scenario when the yarn command is present in PATH but the specific active version of nodejs doesn't have yarn installed)

## Related issues

- https://github.com/flexn-io/renative/issues/806

## Npm releases

n/a

2024-05-23 08:30 UTC, pauliusguzas requested changes
project is created successfully but can't run platform
```
pauliusguzas@MBP-de-Flexn renative % npm uninstall yarn -g

removed 1 package in 494ms
pauliusguzas@MBP-de-Flexn renative % yarn
zsh: command not found: yarn
pauliusguzas@MBP-de-Flexn renative % cd
pauliusguzas@MBP-de-Flexn ~ % cd Desktop
pauliusguzas@MBP-de-Flexn Desktop % rnv new

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 5/23/2024, 11:20:34 AM        │
│ $ rnv new                                                       │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (./renative/renative/packages/engine-core/lib)
task: ○ new ↺1
? What's your project Name? (folder will be created) yarnas
? What workspace to use? rnv
? What template to use? @rnv/template-starter (local) - /Users/pauliusguzas/desktop/renative/renative/packages/template-starter
info: Found local template: @rnv/template-starter@1.0.0-rc.19
✔ Executing: npm install
✔ Executing: npm add @rnv/config-templates@1.0.0-rc.19 --dev
? How to create config renative.json? Extend template (cleaner, overridable)
? What's your project Title? My Renative App
? What's your App ID? com.mycompany.yarnas
? What's your project version? 0.1.0
? What platforms would you like to use? web, ios, android
? Do you want to set-up git in your new project? Yes
info: Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
info: Missing directory ./yarnas/buildHooks.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/entry.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/src/config.tsx.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/index.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/tsconfig.json.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/babel.config.js.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/typings.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/.gitignore.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/base/assets.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/base/fonts.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/Gemfile.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/metro.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/react-native.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/next.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/next-env.d.ts.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/pages.js. COPYING from TEMPATE...DONE
info: .rnv/schemas folder missing. CREATING...DONE
info: Updating appConfig app with title: My Renative App and id: com.mycompany.yarnas
? Project is ready. Do you want to install all dependencies now? Yes
✔ Executing: npm install
? To avoid the issue with the resolving peer dependencies .npmrc file with content: "legacy-peer-deps=true" will be added to your
project Yes
task: ✔ new
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 5/23/2024, 11:27:41 AM | rnv@1.0.0-rc.19            │
│ $ rnv new                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: yarnas@0.1.0                                           │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-core                                        │
│ Template: @rnv/template-starter                                 │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | x64 | node v18.17.0                          │
│ Executed Time: 0h:7m:6s:764ms                                   │
│
  Generated Project Summary:
  -------------------------
  Project Name (--projectName): yarnas
  Package name: yarnas
  Project Version (--appVersion): 0.1.0
  Workspace (--workspace): rnv
  App Title (--title): My Renative App
  App ID (--id): com.mycompany.yarnas
  Project Template (--template): ../desktop/renative/renative/packages/template-starter
  Git Enabled (--gitEnabled): true
  Enabled Platforms: web, ios, android
  -------------------------
  ✔ Your project is ready! Run it with:

  cd yarnas
  npx rnv run
└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn Desktop % cd yarnas
Unknown ruby interpreter version (do not know how to handle): >=2.6.10.
pauliusguzas@MBP-de-Flexn yarnas % rnv link

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 5/23/2024, 11:27:48 AM        │
│ $ rnv link                                                      │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (../renative/renative/packages/engine-core/lib)
task: ○ link ↺1
info: Found following source packages:

./node_modules/@rnv/adapter (unlinked)
./node_modules/@rnv/cli (unlinked)
./node_modules/@rnv/config-templates (unlinked)
./node_modules/@rnv/core (unlinked)
./node_modules/@rnv/engine-core (unlinked)
./node_modules/@rnv/engine-lightning (unlinked)
./node_modules/@rnv/engine-rn (unlinked)
./node_modules/@rnv/engine-rn-electron (unlinked)
./node_modules/@rnv/engine-rn-next (unlinked)
./node_modules/@rnv/engine-rn-tvos (unlinked)
./node_modules/@rnv/engine-rn-web (unlinked)
./node_modules/@rnv/renative (unlinked)
./node_modules/@rnv/sdk-android (unlinked)
./node_modules/@rnv/sdk-apple (unlinked)
./node_modules/@rnv/sdk-kaios (unlinked)
./node_modules/@rnv/sdk-react-native (unlinked)
./node_modules/@rnv/sdk-telemetry (unlinked)
./node_modules/@rnv/sdk-tizen (unlinked)
./node_modules/@rnv/sdk-utils (unlinked)
./node_modules/@rnv/sdk-webos (unlinked)
./node_modules/@rnv/sdk-webpack (unlinked)
./node_modules/@rnv/template-starter (linked)

? Found following packages to link? @rnv/adapter, @rnv/cli, @rnv/config-templates, @rnv/core, @rnv/engine-core, @rnv/engine-lightn
ing, @rnv/engine-rn, @rnv/engine-rn-electron, @rnv/engine-rn-next, @rnv/engine-rn-tvos, @rnv/engine-rn-web, @rnv/sdk-android, @rnv
/sdk-apple, @rnv/sdk-kaios, @rnv/sdk-react-native, @rnv/sdk-telemetry, @rnv/sdk-tizen, @rnv/sdk-utils, @rnv/sdk-webos, @rnv/sdk-we
bpack, @rnv/template-starter
info: Linking packages...
info: ✔ @rnv/adapter (./node_modules/@rnv/adapter)
info: ✔ @rnv/cli (./node_modules/@rnv/cli)
info: ✔ @rnv/config-templates (./node_modules/@rnv/config-templates)
info: ✔ @rnv/core (./node_modules/@rnv/core)
info: ✔ @rnv/engine-core (./node_modules/@rnv/engine-core)
info: ✔ @rnv/engine-lightning (./node_modules/@rnv/engine-lightning)
info: ✔ @rnv/engine-rn (./node_modules/@rnv/engine-rn)
info: ✔ @rnv/engine-rn-electron (./node_modules/@rnv/engine-rn-electron)
info: ✔ @rnv/engine-rn-next (./node_modules/@rnv/engine-rn-next)
info: ✔ @rnv/engine-rn-tvos (./node_modules/@rnv/engine-rn-tvos)
info: ✔ @rnv/engine-rn-web (./node_modules [...]

2024-05-23 08:56 UTC, ElenaDiachenko commented
@pauliusguzas  You don’t need to do `rnv link`. Just run

2024-05-23 09:15 UTC, pauliusguzas requested changes
same issue
```
pauliusguzas@MBP-de-Flexn Desktop % npm uninstall yarn -g

removed 1 package in 486ms
pauliusguzas@MBP-de-Flexn Desktop % rnv new

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 5/23/2024, 12:07:24 PM        │
│ $ rnv new                                                       │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (./renative/renative/packages/engine-core/lib)
task: ○ new ↺1
? What's your project Name? (folder will be created) yarnas
warn:  Folder ./yarnas already exists. RNV will override it.
? Continue? Yes
info: Cleaning up existing folder...
? What workspace to use? rnv
? What template to use? @rnv/template-starter (local) - /Users/pauliusguzas/desktop/renative/renative/packages/template-starter
info: Found local template: @rnv/template-starter@1.0.0-rc.19
✔ Executing: npm install
✔ Executing: npm add @rnv/config-templates@1.0.0-rc.19 --dev
? How to create config renative.json? Extend template (cleaner, overridable)
? What's your project Title? My Renative App
? What's your App ID? com.mycompany.yarnas
? What's your project version? 0.1.0
? What platforms would you like to use? web, ios, android
? Do you want to set-up git in your new project? Yes
info: Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
info: Missing directory ./yarnas/buildHooks.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/entry.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/src/config.tsx.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/index.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/tsconfig.json.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/babel.config.js.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/typings.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/.gitignore.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/base/assets.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/appConfigs/base/fonts.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/Gemfile.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/metro.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/react-native.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/next.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./yarnas/next-env.d.ts.js. COPYING from TEMPATE...DONE
info: Missing directory ./yarnas/src/pages.js. COPYING from TEMPATE...DONE
info: .rnv/schemas folder missing. CREATING...DONE
info: Updating appConfig app with title: My Renative App and id: com.mycompany.yarnas
? Project is ready. Do you want to install all dependencies now? Yes
✔ Executing: npm install
? To avoid the issue with the resolving peer dependencies .npmrc file with content: "legacy-peer-deps=true" will be added to your
project Yes
task: ✔ new
┌─────────────────────────────────────────────────────────────────┐
│ ⚠ SUMMARY | 5/23/2024, 12:14:06 PM | rnv@1.0.0-rc.19            │
│ $ rnv new                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: yarnas@0.1.0                                           │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-core                                        │
│ Template: @rnv/template-starter                                 │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | x64 | node v18.17.0                          │
│ Executed Time: 0h:6m:41s:555ms                                  │
│ warn:  Folder ./yarnas already exists. RNV will override it.
│
  Generated Project Summary:
  -------------------------
  Project Name (--projectName): yarnas
  Package name: yarnas
  Project Version (--appVersion): 0.1.0
  Workspace (--workspace): rnv
  App Title (--title): My Renative App
  App ID (--id): com.mycompany.yarnas
  Project Template (--template): ../desktop/renative/renative/packages/template-starter
  Git Enabled (--gitEnabled): true
  Enabled Platforms: web, ios, android
  -------------------------
  ✔ Your project is ready! Run it with:

  cd yarnas
  npx rnv run
└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn Desktop % cd yarnas
Unknown ruby interpreter version (do not know how to handle): >=2.6.10.
pauliusguzas@MBP-de-Flexn yarnas % npx rnv run -p web

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run -p web                                            │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-next (./node_modules/@rnv/engine-rn-next)
task: ○ run ↺1
info: Build hooks not complied. BUILDING...
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
info: Creating folder ./platformBuilds ...DONE
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Found only one app config available. Will use app
info: Current app config: app
task: ✔ app configure
info: Adding missing engine @rnv/engine-rn-next@1.0.0-rc.19 to package.json
info: Adding missing engine @rnv/engine-rn@1.0.0-rc.19 to package.json
info: ✔ /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
info: ✔ /@react-native-community/cli/build/bin.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json. FIXING...DONE
info: ✔ /react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js requires override by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json. FIXING...DONE
info: ✔ /react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js requires override by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json. FIXING...DONE
info: ✔ /react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js requires override by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json. FIXING...DONE
task: ✔ project configure
info: Current Build Scheme: debug
warn: ○ platform configure: Updates to package.json are required:
- react (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-art (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-dom (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-native (N/A) => (0.73.4) Missing dependency | plugin (renative.json)
- react-native-web (N/A) => (0.19.9) Missing dependency | plugin (renative.json)
- next (N/A) => (14.1.4) Missing dependency | plugin (renative.json)
- @rnv/renative (N/A) => (1.0.0-rc.19) Missing dependency | plugin (renative.json)
- react-native- [...]

2024-06-05 10:21 UTC, locksten commented
I modified [isYarnInstalled()](https://github.com/flexn-io/renative/blob/72c67b423a97e2651a8650ed97524c8abe31a1a0/packages/core/src/projects/npm.ts#L120) to always return false (just adding `--packageManager npm` doesn't work but that's a separate issue) and got the same error (with npm v10.2.3).
Seems to be a common [issue](https://github.com/npm/cli/issues/4907) with npm.

2024-07-03 06:18 UTC, GabrieleKaceviciute commented
1. `rnv new` ->
```
➜  nauji rnv new

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 7/3/2024, 9:05:15 AM          │
│ $ rnv new                                                       │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (../tests/renative/packages/engine-core/lib)
task: ○ new ↺1
? What's your project Name? (folder will be created) hello-renative
? What workspace to use? rnv
? What template to use? @rnv/template-starter (local) - /Users/gabriele/Desktop/tests/renative/packages/template-starter
info: Found local template: @rnv/template-starter@1.0.0-rc.19
✔ Executing: npm install
✔ Executing: npm add @rnv/config-templates@1.0.0-rc.19 --dev
? How to create config renative.json? Extend template (cleaner, overridable)
? What's your project Title? My Renative App
? What's your App ID? com.mycompany.hellorenative
? What's your project version? 0.1.0
? What platforms would you like to use? web, ios, android
? Do you want to set-up git in your new project? Yes
info: Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
info: Missing directory ./hello-renative/buildHooks.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/src/app.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/src/entry.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/src/config.tsx.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/index.js.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/tsconfig.json.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/babel.config.js.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/typings.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/.gitignore.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/appConfigs/app.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/appConfigs/base/assets.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/appConfigs/base/fonts.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/Gemfile.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/metro.config.js.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/react-native.config.js.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/next.config.js.js. COPYING from TEMPLATE...DONE
info: Missing file ./hello-renative/next-env.d.ts.js. COPYING from TEMPLATE...DONE
info: Missing directory ./hello-renative/src/pages.js. COPYING from TEMPLATE...DONE
info: .rnv/schemas folder missing. CREATING...DONE
info: Updating appConfig app with title: My Renative App and id: com.mycompany.hellorenative
? To avoid the issue with the resolving peer dependencies .npmrc file with content: "legacy-peer-deps=true" will be added to your project Yes
? You do not have any engines installed. Do you want to install them now? Yes
⠼ Executing: npm add @rnv/engine-rn-next@1.0.0-rc.19 --dev
✔ Executing: npm add @rnv/engine-rn-next@1.0.0-rc.19 --dev
✔ Executing: npm add @rnv/engine-rn@1.0.0-rc.19 --dev
? Project is ready. Do you want to install all dependencies now? Yes
✔ Executing: npm install
task: ✔ new
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 7/3/2024, 9:08:19 AM | rnv@1.0.0-rc.19              │
│ $ rnv new                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: hello-renative@0.1.0                                   │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-core                                        │
│ Template: @rnv/template-starter                                 │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:3m:3s:871ms                                   │
│
  Generated Project Summary:
  -------------------------
  Project Name (--projectName): hello-renative
  Package name: hello-renative
  Project Version (--appVersion): 0.1.0
  Workspace (--workspace): rnv
  App Title (--title): My Renative App
  App ID (--id): com.mycompany.hellorenative
  Project Template (--template): ../tests/renative/packages/template-starter
  Git Enabled (--gitEnabled): true
  Enabled Platforms: web, ios, android
  -------------------------
  ✔ Your project is ready! Run it with:

  cd hello-renative
  npx rnv run
└─────────────────────────────────────────────────────────────────┘
```
2. `npx rnv run -p web` -> pass
3. `npx rnv run -p android` -> 
```
➜  hello-renative git:(master) ✗ npx rnv run -p android

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run -p android                                        │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn (./node_modules/@rnv/engine-rn)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: app
task: ✔ app configure
info: ./node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ./node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
info: Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/android. Will be used to generate assets.
✔ Executing: npx jetify
task: ✔ configure
✔ Executing: /Users/gabriele/Library/Android/sdk/platform-tools/adb devices -l
✔ Executing: /Users/gabriele/Library/Android/sdk/emulator/emulator -list-avds
✔ Executing: /Users/gabriele/Library/Android/sdk/platform-tools/adb devices -l
✔ Waiting for emulator to boot...
✔ Executing: /Users/gabriele/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell wm size
✔ Executing: /Users/gabriele/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell wm density
✔ Executing: /Users/gabriele/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
info: ✔ Found active emulator! emulator-5554. Will use it
task: ○ start ↺1
task: ○ configureSoft ↺1
task: ○ app configure ↺2
info: Current app config: app
task: ✔ app configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺2
task: ✔ sdk configure
task: ✔ configureSoft

Dev server running at: http://0.0.0.0:8083/index.bundle?platform=android

task: ✔ start
⠇ Waiting for bundler to finish...warn =================================================================================================
warn From React Native 0.73, your project's Metro config should extend '@react-native/me [...]

2024-07-03 07:42 UTC, GabrieleKaceviciute approved these changes

2024-07-03 07:57 UTC, pavjacko approved these changes

2024-07-03 07:57 UTC, merged