fix/kaios_defaultTarget
flexn-io/renative pull request #1602
Opened 2024-06-07 10:24 UTC by ElenaDiachenko

## Description

- [kaios] Rnv asks to pick simulator even default target is defined 

## Related issues

- https://github.com/flexn-io/renative/issues/1586

## Npm releases

n/a

2024-06-07 10:54 UTC, pauliusguzas requested changes
If the target is wrong or there is no target it should ask to choose like it did previously

2024-06-07 12:17 UTC, pauliusguzas approved these changes

2024-06-12 06:44 UTC, locksten approved these changes

2024-06-13 07:43 UTC, pavjacko approved these changes

2024-06-13 07:43 UTC, merged