Webos cli installation check
flexn-io/renative pull request #1606
Opened 2024-06-11 06:16 UTC by justinasRm

## Description

- Webos cli has been udated and not is installed with npm. Before it was installed with the emulator, so the check for it wasn't working on the newer version.

## Related issues

- #1600

## Npm releases

n/a

2024-06-12 06:30 UTC, pauliusguzas requested changes
target list and run fail when cli installed using npm
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p webos

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 6/12/2024, 9:27:36 AM         │
│ $ rnv run -p webos                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: template
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/webos. Will be used to generate assets.
task: ✔ configure
info: Your webos devServer at port 8088 is not running. Starting it up for you...
info: Your webos devServerHost 127.0.0.1 at port 8088 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 6/12/2024, 9:27:37 AM | rnv@1.0.0-rc.19     │
│ $ rnv run -p webos                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0-rc.19                      │
│ Workspace: rnv                                                  │
│ Platform (-p): webos                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Target (-t): emulator                                           │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:0s:899ms                                   │
│ Project location: ./platformBuilds/template_webos               │
└─────────────────────────────────────────────────────────────────┘
(node:8480) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:8480) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8088
  On Your Network:  http://192.168.8.181:8088

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.47 MiB
  asset static/js/bundle.js 3.16 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.88 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
runtime modules 28.8 KiB 14 modules
modules by path ../ 859 KiB 447 modules
modules by path ./ 1.81 MiB (javascript) 315 KiB (asset)
  modules by path ./node_modules/react-native-web/dist/ 710 KiB 196 modules
  modules by path ./platformAssets/ 3.35 KiB (javascript) 12.1 KiB (asset) 4 modules
  modules by path ./src/ 14.5 KiB
    ./src/entry/index.web.tsx 1.49 KiB [built] [code generated]
    + 2 modules
  modules by path ./node_modules/react-dom/ 1.07 MiB
    ./node_modules/react-dom/client.js 620 bytes [built] [code generated]
    + 2 modules
  modules by path ./node_modules/scheduler/ 19 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.development.js 18.8 KiB [built] [code generated]
  + 4 modules
webpack 5.91.0 compiled successfully in 4519 ms
No issues found.
✔ Executing: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-package -o /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos/output /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos -n
✖ FAILED: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device-info -D
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
COMMAND:

/Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device-info -D

FAILED with ERROR:

Error: Command failed with exit code 255: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device-info -D
ares-device-info ERR! [Tips]: This command is deprecated. Please use "ares-device" instead of "ares-device-info"
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


COMMAND:

/Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device-info -D

FAILED with ERROR:

Error: Command failed with exit code 255: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device-info -D
ares-device-info ERR! [Tips]: This command is deprecated. Please use "ares-device" instead of "ares-device-info"
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


pauliusguzas@MBP-de-Flexn template-starter % npx rnv target list -p webos

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚██ [...]

2024-06-12 08:01 UTC, pauliusguzas requested changes
```pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p webos

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.19 | renative.org | 6/12/2024, 11:00:44 AM        │
│ $ rnv run -p webos                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: template
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/webos. Will be used to generate assets.
task: ✔ configure
info: Your webos devServer at port 8088 is not running. Starting it up for you...
info: Your webos devServerHost 127.0.0.1 at port 8088 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 6/12/2024, 11:00:44 AM | rnv@1.0.0-rc.19    │
│ $ rnv run -p webos                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0-rc.19                      │
│ Workspace: rnv                                                  │
│ Platform (-p): webos                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Target (-t): emulator                                           │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:0s:750ms                                   │
│ Project location: ./platformBuilds/template_webos               │
└─────────────────────────────────────────────────────────────────┘
(node:24894) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:24894) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8088
  On Your Network:  http://192.168.8.181:8088

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.47 MiB
  asset static/js/bundle.js 3.16 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.88 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
cached modules 2.64 MiB (javascript) 303 KiB (asset) 28.8 KiB (runtime) [cached] 671 modules
modules by layer 2.03 KiB (javascript) 12.1 KiB (asset)
  ./platformAssets/runtime/fontManager.web.js 1.99 KiB [built]
  ./platformAssets/runtime/logo.png 42 bytes (javascript) 12.1 KiB (asset) [built]
webpack 5.91.0 compiled successfully in 1229 ms
No issues found.
✔ Executing: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-package -o /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos/output /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos -n
✔ Executing: /Users/pauliusguzas/.nvm/versions/node/v18.18.0/bin/ares-device -D
? What device would you like to start the app? (Use arrow keys)
❯ webOS_TV2 - prisoner@192.168.1.30:9922
  webOS_TV - prisoner@192.168.1.24:9922
  emulator - (default)
  webOS_TV3 - prisoner@192.168.1.5:9922
```
run doesn't display simulator option

2024-06-20 09:44 UTC, pauliusguzas commented
it works on device and on sim, only whole logic needs to be improved

2024-07-02 10:23 UTC, pauliusguzas approved these changes

2024-07-03 07:11 UTC, pavjacko approved these changes

2024-07-03 07:12 UTC, merged