Fix/path space
flexn-io/renative pull request #1624
Opened 2024-07-10 06:38 UTC by ElenaDiachenko

## Description

- Small description

## Related issues

- GH issues

## Npm releases

n/a

2024-07-16 07:05 UTC, locksten requested changes

2024-07-16 07:05 UTC, locksten commented on packages/cli/src/logger/index.ts
> +export const logWarning = (msg: string | boolean | unknown, shouldSanitizePath = false) => {
It seems like shouldSanitizePath is backwards here? And using an options object like
```
export const logWarning = (msg: string | boolean | unknown, opts?: { skipSanitizePaths?: boolean }) => {
```
would make the usage clearer.

2024-07-16 13:05 UTC, pauliusguzas approved these changes

2024-07-17 06:58 UTC, locksten requested changes

2024-07-17 06:58 UTC, locksten commented on packages/cli/src/logger/index.ts
> +    const msgSn = typeof msg === 'string' && !shouldSanitizePath ? _sanitizePaths(msg) : String(msg);
This seems to still be backwards? `if not shouldSanitizePath`, then it sanitizes paths?

2024-07-17 10:01 UTC, locksten approved these changes

2024-07-17 10:01 UTC, merged