added 'info env' task using envinfo
flexn-io/renative pull request #1632
Opened 2024-07-17 20:28 UTC by ElenaDiachenko

## Description

- Small description

## Related issues

- https://github.com/flexn-io/renative/issues/74

## Npm releases

n/a

<img width="693" alt="Screenshot 2024-07-17 at 23 26 13" src="https://github.com/user-attachments/assets/38c0061a-da62-444a-a95d-13678b639f21">

2024-07-23 18:00 UTC, pavjacko requested changes

2024-07-23 18:00 UTC, pavjacko commented on packages/engine-core/src/tasks/global/__tests__/taskInfo.test.ts
@ElenaDiachenko consider changing the scope of tests.

instead of testing what could be considered an internal structure of task:
```
import { _checkAndConfigureTargetSdk, _formatObject, _getCliVersions } from '../taskInfo';
```

import task itself 
```
import taskInfo from '../taskInfo';
```

and create test case scenarios around it.

that way what is tested (taskInfo) is treated as blackbox because nobody will use `_checkAndConfigureTargetSdk, _formatObject, _getCliVersions` directly (those should be non-expoted methods internal to task). 
the method you want to test in this case would be `taskClean.fn()` because that's the public api called by anybody who uses this task

example:
https://github.com/flexn-io/renative/blob/main/packages/engine-core/src/tasks/global/__tests__/taskClean.test.ts#L35

2024-07-24 11:26 UTC, pavjacko approved these changes

2024-07-29 06:41 UTC, pauliusguzas commented
```
pauliusguzas@MacBook-Pro-de-Flexn template-starter % npx rnv info

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.21 | renative.org | 7/29/2024, 9:38:59 AM         │
│ $ rnv info                                                      │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (../engine-core/lib)
task: ○ info ↺1
✔ Executing: "/opt/webOS_TV_SDK/CLI/bin/ares" --version
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" version
task: ✔ info
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 7/29/2024, 9:39:09 AM | rnv@1.0.0-rc.21             │
│ $ rnv info                                                      │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0-rc.21                      │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-core                                        │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:9s:847ms                                   │
│

System:
  OS: macOS 13.5.2
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 6.28 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.0/bin/yarn
  npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: 2023.03.27.00 - /usr/local/bin/watchman
Managers:
  CocoaPods: 1.14.3 - ../../../../../.rvm/gems/ruby-3.1.1/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
  Android SDK:
    API Levels: 28, 29, 30, 31, 32, 33, 34
    Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0
    System Images: android-27 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Wear OS 3 Intel x86 Atom, android-31 | Android TV Intel x86 Atom, android-31 | Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode: 15.2/15C500b - /usr/bin/xcodebuild
Languages:
  Java: 17.0.10 - /usr/bin/javac
  Ruby: 3.1.1 - ../../../../../.rvm/rubies/ruby-3.1.1/bin/ruby
npmGlobalPackages:
  rnv: 1.0.0-rc.21
CLI:
  WEBOS CLI: 1.12.4 - /opt/webOS_TV_SDK/CLI/bin/ares
  TIZEN CLI: 2.5.25 - ../../../../../tizen-studio/tools/ide/bin/tizen

└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MacBook-Pro-de-Flexn template-starter % npx rnv info env

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.21 | renative.org | 7/29/2024, 9:39:34 AM         │
│ $ rnv info env                                                  │
└─────────────────────────────────────────────────────────────────┘
info: Did not find exact match for info env. Running interactive wizard for sub-tasks
? Pick a command info env
  No results...
```
@ElenaDiachenko I see you used `info env` command, but for me only `info` works

2024-07-29 06:45 UTC, ElenaDiachenko commented
@pauliusguzas Correct command is` info`.

2024-07-29 06:49 UTC, pauliusguzas approved these changes

2024-08-12 07:08 UTC, merged