[Tizen] run fails on simulator on Windows and Ubuntu
flexn-io/renative pull request #1654
Opened 2024-08-19 07:01 UTC by Marius456

## Description

- Fix tizen simulator for windows and linux.

## Related issues

- https://github.com/flexn-io/renative/issues/1487

## Npm releases

n/a

2024-08-20 07:05 UTC, aurimasmi approved these changes

2024-08-20 13:35 UTC, pauliusguzas requested changes
Same error as in original ticket comment appears

2024-08-26 07:58 UTC, Marius456 commented
@pauliusguzas The problem occurs only when you try to run old version of tizen(like 7). Old versions are not officially supported and you can't install them anymore.

2024-08-26 16:02 UTC, pauliusguzas approved these changes

2024-08-27 07:16 UTC, merged