improve regex overrides
flexn-io/renative pull request #1694
Opened 2024-09-05 21:35 UTC by ElenaDiachenko

## Description

- Regex overrides improvements (prevent duplication)

## Related issues

- https://github.com/flexn-io/renative/issues/1691

## Npm releases

n/a

2024-09-06 08:44 UTC, locksten requested changes
Adding marker comments like this:
```ts
import * as NativeComponentRegistry from '../../NativeComponent/NativeComponentRegistry';
import {ConditionallyIgnoredEventHandlers} from '../../NativeComponent/ViewConfigIgnore';
import Platform from '../../Utilities/Platform';/*RNV*/
import NativeModules from '../../BatchedBridge/NativeModules';/*RNV*/
```
would break overrides in files that don't support `/**/` comments, like `.podspec` or `.properties`, as well as overrides in multiline strings or macros.
But in most use cases it would be fine, so just restricting it to languages that support `/**/` comments might be enough, but it would make overrides work inconsistently.

2024-09-12 10:51 UTC, locksten requested changes

2024-09-12 10:51 UTC, locksten commented on packages/core/src/plugins/index.ts
> +        const markerComment = '/*RNV*/';
Are the `/*RNV*/` marker comments still necessary now that overrides are applied to originals?

2024-09-12 10:51 UTC, locksten commented on packages/core/src/plugins/index.ts
> +    return '';
Why does this `return ''` while `_saveOriginalFile` throws an error?

2024-09-12 10:51 UTC, locksten commented on packages/engine-core/src/tasks/patch/taskPatchReset.ts
> +        const appliedOverrideFilePath = path.join(overrideDir, 'applied_overrides.json');
Is it expected that `patch reset` does not revert file-based overrides, only `overrides.json`? If so, the description should specify that, and it should maybe print a warning.

2024-09-12 10:51 UTC, locksten commented on packages/core/src/plugins/index.ts
> +        if (overridesChanged && !isFirstRun) {
It seems like after reinstalling node_modules or updating a package, overrides don't get applied to the new clean node_modules files. And after changing an override, an outdated backup is restored and then overridden.

2024-09-18 06:58 UTC, locksten reviewed
The `resetOverrides` hook won't automatically run in users' projects. What exactly is it's purpose? What's the difference between it and `taskPatchReset`?

---

It seems like overrides are also applied to subdependencies now:
```json
"@react-native-community/cli": {},
"react-native/node_modules/@react-native-community/cli": {},
"react-native-tvos/node_modules/@react-native-community/cli": {},
```
but weren't before (in b16b40ce0cb5458b3e61417fd5cb9c4759142c7c):
```json
"@react-native-community/cli": {},
```
@RicardasN  had an issue with overriding subdependencies a little while ago. Is this an intentional change for that?

2024-09-19 07:01 UTC, locksten approved these changes

2024-09-19 09:26 UTC, pauliusguzas approved these changes
just merge e2e file changes from main

2024-09-19 10:33 UTC, merged