fix default target setting for webos + select it to run if available
flexn-io/renative pull request #1728
Opened 2024-09-25 12:54 UTC by ElenaDiachenko

## Description

- [webos] default target isn't applied when more than 1 webos target available

## Related issues

- https://github.com/flexn-io/renative/issues/1722

## Npm releases

n/a

2024-09-25 15:57 UTC, pauliusguzas requested changes
still failing
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p webos

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.3.0-rc.0 | renative.org | 9/25/2024, 6:56:31 PM          │
│ $ rnv run -p webos                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: template
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/webos. Will be used to generate assets.
task: ✔ configure
info: Your webos devServer at port 8088 is not running. Starting it up for you...
info: Your webos devServerHost 127.0.0.1 at port 8088 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 9/25/2024, 6:56:34 PM | rnv@1.3.0-rc.0      │
│ $ rnv run -p webos                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.3.0-rc.0                       │
│ Workspace: rnv                                                  │
│ Platform (-p): webos                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Target (-t): webOS_TV_23_Simulator_1.4.0                        │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:2s:582ms                                   │
│ Project location: ./platformBuilds/template_webos               │
└─────────────────────────────────────────────────────────────────┘
(node:12943) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:12943) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8088
  On Your Network:  http://192.168.1.33:8088

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.48 MiB
  asset static/js/bundle.js 3.17 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.88 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
cached modules 2.65 MiB (javascript) 303 KiB (asset) 28.8 KiB (runtime) [cached] 671 modules
modules by layer 2.01 KiB (javascript) 12.1 KiB (asset)
  ./platformAssets/runtime/fontManager.web.js 1.97 KiB [built]
  ./platformAssets/runtime/logo.png 42 bytes (javascript) 12.1 KiB (asset) [built]
webpack 5.94.0 compiled successfully in 1307 ms
No issues found.
✔ Executing: "/opt/webOS_TV_SDK/CLI/bin/ares-package" -o "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos/output" "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_webos" -n
✔ Executing: "/opt/webOS_TV_SDK/CLI/bin/ares-device-info" -D
✔ Executing: "/opt/webOS_TV_SDK/CLI/bin/ares-launch" -V
? Found several installed simulators. Choose which one to use: (Use arrow keys)
❯ webOS_TV_23_Simulator_1.3.0
  webOS_TV_24_Simulator_1.4.1
```

2024-09-25 15:59 UTC, pauliusguzas approved these changes

2024-09-25 15:59 UTC, pauliusguzas commented
mistake was made in previous testing

2024-09-26 08:39 UTC, Marius456 approved these changes

2024-09-26 08:39 UTC, merged