fix google cast not working
flexn-io/renative pull request #1738
Opened 2024-09-30 17:03 UTC by locksten

## Description

Added `DISABLE_DISCOVERY_AUTOSTART` and `START_DISCOVERY_AFTER_FIRST_TAP_ON_CAST_BUTTON` plugin props.
Added a separate "Load Media" button, since with google cast connecting to a device and playing media on it are separate actions.
Replaced `useRemoteMediaClient` with `CastContext`, since on ios google cast hooks seem to not refresh.
Added debug logging.

https://github.com/user-attachments/assets/65d76ea4-c8b8-4b15-a4de-a6a33816c76a

https://github.com/user-attachments/assets/6c384720-6b59-47a6-b2b1-d4d4f9f29f21

## Related issues

- https://github.com/flexn-io/renative/issues/1553

2024-10-01 07:21 UTC, RicardasN approved these changes

2024-10-01 14:21 UTC, pauliusguzas requested changes
tvos fails to run and androidtv has also chromecast support, is that expected?

2024-10-07 07:03 UTC, Marius456 approved these changes

2024-10-07 07:04 UTC, pauliusguzas approved these changes

2024-10-07 07:05 UTC, merged