fix/choosing_apple_device
flexn-io/renative pull request #1753
Opened 2024-10-09 13:01 UTC by ElenaDiachenko

## Description

- [ios, tvos] npx rnv run -p ios -d -t random installs app when 1 device is connected
- [ios, tvos] npx rnv run -p ios -d -t doesn't ask to choose from device list when 1 device is available
- [ios, tvos] npx rnv run -p ios -t asks only simulators

## Related issues

- https://github.com/flexn-io/renative/issues/1741
- https://github.com/flexn-io/renative/issues/1740

## Npm releases

n/a

2024-10-10 08:57 UTC, GabrieleKaceviciute requested changes
at least one device is active:
- `npx rnv run -p ios -t device name` -> doesn't find device. Expected - install to specified device.
- `npx rnv run -p ios -t random` -> asks from simulators. Expected - ask from simulators and active devices.
- `npx rnv run -p ios -d -t device IP` -> asks from active device. Expected - install to specified device.
- `npx rnv run -p ios -t device IP` -> asks from simulators. Expected - install to specified device.
- `npx rnv run -p ios -t random IP` -> asks from simulators. Expected - ask from simulators and active devices.

Note: same on tvos.

2024-10-14 16:53 UTC, GabrieleKaceviciute approved these changes

2024-10-16 07:09 UTC, aurimasmi approved these changes

2024-10-16 07:09 UTC, aurimasmi commented on packages/sdk-apple/src/runner.ts
> +    const { device, target } = c.program.opts();
can simplify like:

```
const devicesArr = await getAppleDevices(false, device ? true : false);
```

2024-10-17 08:32 UTC, merged