fix change cert in new project
flexn-io/renative pull request #1758
Opened 2024-10-17 13:50 UTC by Marius456

## Description

- Small description

## Related issues

- GH issues

## Npm releases

n/a

2024-10-17 14:48 UTC, pauliusguzas requested changes
tested with linked template and getting same error

2024-10-17 15:43 UTC, Marius456 commented
> tested with linked template and getting same error

Can you give steps that you did? Did you use `rnv link`?

2024-10-17 15:57 UTC, pauliusguzas approved these changes
my bad, forgot to do rnv link, works now

2024-10-18 07:19 UTC, locksten approved these changes

2024-10-18 07:58 UTC, merged