[kaios] Fix default target
flexn-io/renative pull request #1817
Opened 2024-12-04 11:11 UTC by Marius456

## Description

- Add functionality to update default target for KaiOS

## Related issues

- https://github.com/flexn-io/renative/issues/1802

## Npm releases

n/a

2024-12-06 08:05 UTC, pauliusguzas commented
The defaultTarget itself seems to be working, but kaios simulator is being looked for at weird path
![image](https://github.com/user-attachments/assets/b59224be-419c-48d2-a303-cd4d4c0d1114)

And also weird target is being added to renative.json
![image](https://github.com/user-attachments/assets/c7d5b18c-ba8e-4f40-a600-eaa814cc4ab4)

2024-12-06 08:05 UTC, pauliusguzas requested changes
The defaultTarget itself seems to be working, but kaios simulator is being looked for at weird path
![image](https://github.com/user-attachments/assets/b59224be-419c-48d2-a303-cd4d4c0d1114)

And also weird target is being added to renative.json (last one)
![image](https://github.com/user-attachments/assets/c7d5b18c-ba8e-4f40-a600-eaa814cc4ab4)

Full renative.json below
![XsKueFY4](https://github.com/user-attachments/assets/b4ad7aa0-7e22-4752-a452-ea00526d5158)

2024-12-06 09:43 UTC, Marius456 commented
`KAIOS_SDK` should be only until `Downloads` folder: `/home/testlab-ubuntu/Downloads`

From kaios simulator side the problem is that by unzipping differently you get 2 unique folders. So it should be `kaiosrt.v2.5-us-US.linux-x86_64` in `Downloads` folder.

2024-12-08 20:45 UTC, pauliusguzas approved these changes

2024-12-09 09:05 UTC, locksten approved these changes

2024-12-10 07:47 UTC, merged